### ISSUE TITLE
Verible Installed?

### ISSUE THREAD

**Issue by sjkelly** [librecores/gh-action#1]
I have a GitHub actions file like so:

```
# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. Triggers the workflow on push or pull request
# events but only for the master branch
on: [push, pull_request]

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
  # This workflow contains a single job called "build"
  lint:
    # The type of runner that the job will run on
    runs-on: ubuntu-latest

    # Steps represent a sequence of tasks that will be executed as part of the job
    steps:
    # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
    - name: Checkout
      uses: actions/checkout@v1
    # Runs a single command using the runners shell
    - name: Lint Verilog source files with Verible
      uses: librecores/ci-action@2020.6-rc1
      with:
        command: verible-verilog-lint *.v
```

The action appears to not have verible installed: https://github.com/google/verible
Are there some examples of this action being used in other repos?
